name: Check uv.lock is up to date

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  check-uv-lock:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Check if uv.lock is up to date
        run: |
          uv lock
          if [ -n "$(git diff --name-only uv.lock)" ]; then
            echo "uv.lock is out of date. Please run 'uv lock' and commit the changes."
            exit 1
          fi
        shell: bash
